"""added a bunch of graph vars for assignee

Revision ID: 11a00705ac61
Revises: 48044ce97c4f
Create Date: 2013-04-08 10:21:12.247290

"""

# revision identifiers, used by Alembic.
revision = '11a00705ac61'
down_revision = '48044ce97c4f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bugmonths', sa.Column('assignee_constraint_prior_month', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bugmonths', 'assignee_constraint_prior_month')
    ### end Alembic commands ###
