"""new bugsdebuggers columns

Revision ID: 21ca52dc7a
Revises: 4f1a9eeed5c3
Create Date: 2013-04-20 16:04:08.420014

"""

# revision identifiers, used by Alembic.
revision = '21ca52dc7a'
down_revision = '4f1a9eeed5c3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bugmonths', sa.Column('bugs_debuggers_effective_size_churn_cumulative', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_alter_churn_past_monthly_avg', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_alter_churn_cumulative', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_outdegree_past_monthly_avg', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_efficiency_past_monthly_avg', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_clustering_past_monthly_avg', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_clustering_prior_month', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_closeness_past_monthly_avg', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_alter_churn_prior_month', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_efficiency_prior_month', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_closeness_prior_month', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_effective_size_churn_past_monthly_avg', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_betweenness_prior_month', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_effective_size_churn_prior_month', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_outdegree_prior_month', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_effective_size_past_monthly_avg', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_effective_size_prior_month', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_constraint_past_monthly_avg', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_indegree_prior_month', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_constraint_prior_month', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_betweenness_past_monthly_avg', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_indegree_past_monthly_avg', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bugmonths', 'bugs_debuggers_indegree_past_monthly_avg')
    op.drop_column('bugmonths', 'bugs_debuggers_betweenness_past_monthly_avg')
    op.drop_column('bugmonths', 'bugs_debuggers_constraint_prior_month')
    op.drop_column('bugmonths', 'bugs_debuggers_indegree_prior_month')
    op.drop_column('bugmonths', 'bugs_debuggers_constraint_past_monthly_avg')
    op.drop_column('bugmonths', 'bugs_debuggers_effective_size_prior_month')
    op.drop_column('bugmonths', 'bugs_debuggers_effective_size_past_monthly_avg')
    op.drop_column('bugmonths', 'bugs_debuggers_outdegree_prior_month')
    op.drop_column('bugmonths', 'bugs_debuggers_effective_size_churn_prior_month')
    op.drop_column('bugmonths', 'bugs_debuggers_betweenness_prior_month')
    op.drop_column('bugmonths', 'bugs_debuggers_effective_size_churn_past_monthly_avg')
    op.drop_column('bugmonths', 'bugs_debuggers_closeness_prior_month')
    op.drop_column('bugmonths', 'bugs_debuggers_efficiency_prior_month')
    op.drop_column('bugmonths', 'bugs_debuggers_alter_churn_prior_month')
    op.drop_column('bugmonths', 'bugs_debuggers_closeness_past_monthly_avg')
    op.drop_column('bugmonths', 'bugs_debuggers_clustering_prior_month')
    op.drop_column('bugmonths', 'bugs_debuggers_clustering_past_monthly_avg')
    op.drop_column('bugmonths', 'bugs_debuggers_efficiency_past_monthly_avg')
    op.drop_column('bugmonths', 'bugs_debuggers_outdegree_past_monthly_avg')
    op.drop_column('bugmonths', 'bugs_debuggers_alter_churn_cumulative')
    op.drop_column('bugmonths', 'bugs_debuggers_alter_churn_past_monthly_avg')
    op.drop_column('bugmonths', 'bugs_debuggers_effective_size_churn_cumulative')
    ### end Alembic commands ###
