"""changed debuggermonths columns

Revision ID: 22f06ad17c2f
Revises: 572da8d82c38
Create Date: 2013-04-20 16:43:40.811164

"""

# revision identifiers, used by Alembic.
revision = '22f06ad17c2f'
down_revision = '572da8d82c38'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
