"""empty message

Revision ID: 265286722d68
Revises: None
Create Date: 2013-03-12 12:39:57.068276

"""

# revision identifiers, used by Alembic.
revision = '265286722d68'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'bugmonths')
    op.add_column('bugevents', sa.Column('orig', sa.Enum(['hist', 'comment']), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bugevents', 'orig')
    op.create_table(u'bugmonths',
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.Column(u'bugid', sa.INTEGER(), nullable=True),
    sa.Column(u'monthid', sa.INTEGER(), nullable=True),
    sa.Column(u'assigneeid', sa.INTEGER(), nullable=True),
    sa.Column(u'bsid', sa.INTEGER(), nullable=True),
    sa.Column(u'status', sa.VARCHAR(length=11), nullable=True),
    sa.Column(u'resolution', sa.VARCHAR(length=10), nullable=True),
    sa.Column(u'nmonths_since_reported', sa.INTEGER(), nullable=True),
    sa.Column(u'importance', sa.VARCHAR(), nullable=True),
    sa.Column(u'n_dependencies', sa.INTEGER(), nullable=True),
    sa.Column(u'n_blocks', sa.INTEGER(), nullable=True),
    sa.Column(u'n_duplicates', sa.INTEGER(), nullable=True),
    sa.Column(u'platform', sa.VARCHAR(), nullable=True),
    sa.Column(u'product', sa.VARCHAR(), nullable=True),
    sa.Column(u'assigned', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['assigneeid'], [u'debuggers.id'], ),
    sa.ForeignKeyConstraint(['bsid'], [u'bugstates.id'], ),
    sa.ForeignKeyConstraint(['bugid'], [u'bugs.bzid'], ),
    sa.ForeignKeyConstraint(['monthid'], [u'months.id'], ),
    sa.PrimaryKeyConstraint(u'id')
    )
    ### end Alembic commands ###
