"""the last revision evar?

Revision ID: 2f7044d499c3
Revises: 51a6d95c0ef
Create Date: 2013-04-25 11:45:05.618180

"""

# revision identifiers, used by Alembic.
revision = '2f7044d499c3'
down_revision = '51a6d95c0ef'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bugmonths', sa.Column('assginee_nirc_undirected_cumulative', sa.Integer(), nullable=True))
    op.add_column('bugmonths', sa.Column('assignee_nirc_undirected_prior_month', sa.Integer(), nullable=True))
    op.add_column('bugmonths', sa.Column('assignee_nirc_undirected_past_monthly_avg', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('assignee_nreported_cumulative', sa.Integer(), nullable=True))
    op.add_column('bugmonths', sa.Column('assignee_nreported_past_monthly_avg', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('assignee_nreported_prior_month', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bugmonths', 'assignee_nreported_prior_month')
    op.drop_column('bugmonths', 'assignee_nreported_past_monthly_avg')
    op.drop_column('bugmonths', 'assignee_nreported_cumulative')
    op.drop_column('bugmonths', 'assignee_nirc_undirected_past_monthly_avg')
    op.drop_column('bugmonths', 'assignee_nirc_undirected_prior_month')
    op.drop_column('bugmonths', 'assginee_nirc_undirected_cumulative')
    ### end Alembic commands ###
