"""bugmonths!

Revision ID: 3c99135f0c68
Revises: 265286722d68
Create Date: 2013-03-14 17:33:15.953762

"""

# revision identifiers, used by Alembic.
revision = '3c99135f0c68'
down_revision = '265286722d68'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bugmonths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bugid', sa.Integer(), nullable=True),
    sa.Column('monthid', sa.Integer(), nullable=True),
    sa.Column('assigneeid', sa.Integer(), nullable=True),
    sa.Column('bsid', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('UNCONFIRMED', 'NEW', 'READY', 'ASSIGNED', 'REOPENED', 'RESOLVED', 'VERIFIED', 'CLOSED'), nullable=True),
    sa.Column('resolution', sa.Enum('---', 'FIXED', 'INVALID', 'WONTFIX', 'DUPLICATE', 'WORKSFORME', 'INCOMPLETE', 'SUPPORT', 'EXPIRED', 'MOVED'), nullable=True),
    sa.Column('nmonths_since_reported', sa.Integer(), nullable=True),
    sa.Column('importance', sa.String(), nullable=True),
    sa.Column('n_dependencies', sa.Integer(), nullable=True),
    sa.Column('n_blocks', sa.Integer(), nullable=True),
    sa.Column('n_duplicates', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('product', sa.String(), nullable=True),
    sa.Column('assigned', sa.Boolean(), nullable=True),
    sa.Column('assignee_nbugs_prior_month', sa.Integer(), nullable=True),
    sa.Column('assignee_nbugs_past_monthly_avg', sa.Float(), nullable=True),
    sa.Column('assignee_nbugs_past_cumulative', sa.Integer(), nullable=True),
    sa.Column('assignee_nhistoryevents_focal_prior_month', sa.Integer(), nullable=True),
    sa.Column('assignee_nhistoryevents_focal_past_monthly_avg', sa.Float(), nullable=True),
    sa.Column('assignee_nhistoryevents_focal_past_cumulative', sa.Integer(), nullable=True),
    sa.Column('assignee_nhistoryevents_other_prior_month', sa.Integer(), nullable=True),
    sa.Column('assignee_nhistoryevents_other_past_monthly_avg', sa.Float(), nullable=True),
    sa.Column('assignee_nhistoryevents_other_past_cumulative', sa.Integer(), nullable=True),
    sa.Column('assignee_nirc_links_prior_month', sa.Integer(), nullable=True),
    sa.Column('assignee_nirc_links_past_monthly_avg', sa.Float(), nullable=True),
    sa.Column('assignee_nirc_links_past_cumulative', sa.Integer(), nullable=True),
    sa.Column('assignee_nirc_sent_prior_month', sa.Integer(), nullable=True),
    sa.Column('assignee_nirc_sent_past_monthly_avg', sa.Float(), nullable=True),
    sa.Column('assignee_nirc_sent_past_cumulative', sa.Integer(), nullable=True),
    sa.Column('assignee_nirc_received_prior_month', sa.Integer(), nullable=True),
    sa.Column('assignee_nirc_received_past_monthly_avg', sa.Float(), nullable=True),
    sa.Column('assignee_nirc_received_past_cumulative', sa.Integer(), nullable=True),
    sa.Column('ndebuggers_prior_month', sa.Integer(), nullable=True),
    sa.Column('ndebuggers_past_monthly_average', sa.Float(), nullable=True),
    sa.Column('ndebuggers_past_cumulative', sa.Integer(), nullable=True),
    sa.Column('nreported_bugs_prior_month', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigneeid'], ['debuggers.id'], ),
    sa.ForeignKeyConstraint(['bsid'], ['bugstates.id'], ),
    sa.ForeignKeyConstraint(['bugid'], ['bugs.bzid'], ),
    sa.ForeignKeyConstraint(['monthid'], ['months.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bugmonths')
    ### end Alembic commands ###
