"""oop

Revision ID: 40c950a09f42
Revises: 4510b5e6029
Create Date: 2013-04-09 09:36:56.404545

"""

# revision identifiers, used by Alembic.
revision = '40c950a09f42'
down_revision = '4510b5e6029'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debuggermonths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dbid', sa.Integer(), nullable=True),
    sa.Column('monthid', sa.Integer(), nullable=True),
    sa.Column('constraint', sa.Float(), nullable=True),
    sa.Column('closeness', sa.Float(), nullable=True),
    sa.Column('clustering', sa.Float(), nullable=True),
    sa.Column('indegree', sa.Integer(), nullable=True),
    sa.Column('outdegree', sa.Integer(), nullable=True),
    sa.Column('betweenness', sa.Float(), nullable=True),
    sa.Column('effective_size', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['dbid'], ['debuggers.id'], ),
    sa.ForeignKeyConstraint(['monthid'], ['months.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('debuggermonths')
    ### end Alembic commands ###
