"""added pkey for debuggermonths

Revision ID: 4510b5e6029
Revises: 11a00705ac61
Create Date: 2013-04-09 09:34:01.413903

"""

# revision identifiers, used by Alembic.
revision = '4510b5e6029'
down_revision = '11a00705ac61'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
