"""filled out bugs debuggers

Revision ID: 468781521a70
Revises: 22f06ad17c2f
Create Date: 2013-04-23 10:06:19.329455

"""

# revision identifiers, used by Alembic.
revision = '468781521a70'
down_revision = '22f06ad17c2f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_bugs_contributed_to_past_monthly_avg', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_irc_links_past_monthly_avg', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_irc_links_prior_month_avg', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_history_events_other_cumulative', sa.Integer(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_reported_bugs_cumulative', sa.Integer(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_history_events_focal_past_monthly_avg', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_irc_messages_undirected_prior_month_avg', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_irc_messages_directed_prior_month_variance', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_debugger_churn_past_monthly_avg', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_history_events_other_prior_month_variance', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_irc_messages_directed_cumulative', sa.Integer(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_history_events_focal_cumulative', sa.Integer(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_history_events_other_past_monthly_avg', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_irc_messages_undirected_cumulative', sa.Integer(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_history_events_other_prior_month_avg', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_history_events_focal_prior_month_variance', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_bugs_contributed_to_prior_month_avg', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_irc_messages_undirected_prior_month_variance', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_irc_links_prior_month_variance', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_irc_messages_directed_prior_month_avg', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_bugs_contributed_to_cumulative', sa.Integer(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_irc_messages_undirected_past_monthly_avg', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_reported_bugs_past_monthly_avg', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_irc_messages_directed_past_monthly_avg', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_bugs_contributed_to_prior_month_variance', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_history_events_focal_prior_month_avg', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_debugger_churn_cumulative', sa.Integer(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_debuggers_prior_month', sa.Integer(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_irc_links_cumulative', sa.Integer(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_debuggers_past_monthly_avg', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_debuggers_cumulative', sa.Integer(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_reported_bugs_prior_month', sa.Integer(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_debugger_churn_prior_month', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bugmonths', 'bugs_debuggers_debugger_churn_prior_month')
    op.drop_column('bugmonths', 'bugs_debuggers_n_reported_bugs_prior_month')
    op.drop_column('bugmonths', 'bugs_debuggers_n_debuggers_cumulative')
    op.drop_column('bugmonths', 'bugs_debuggers_n_debuggers_past_monthly_avg')
    op.drop_column('bugmonths', 'bugs_debuggers_n_irc_links_cumulative')
    op.drop_column('bugmonths', 'bugs_debuggers_n_debuggers_prior_month')
    op.drop_column('bugmonths', 'bugs_debuggers_debugger_churn_cumulative')
    op.drop_column('bugmonths', 'bugs_debuggers_n_history_events_focal_prior_month_avg')
    op.drop_column('bugmonths', 'bugs_debuggers_n_bugs_contributed_to_prior_month_variance')
    op.drop_column('bugmonths', 'bugs_debuggers_n_irc_messages_directed_past_monthly_avg')
    op.drop_column('bugmonths', 'bugs_debuggers_n_reported_bugs_past_monthly_avg')
    op.drop_column('bugmonths', 'bugs_debuggers_n_irc_messages_undirected_past_monthly_avg')
    op.drop_column('bugmonths', 'bugs_debuggers_n_bugs_contributed_to_cumulative')
    op.drop_column('bugmonths', 'bugs_debuggers_n_irc_messages_directed_prior_month_avg')
    op.drop_column('bugmonths', 'bugs_debuggers_n_irc_links_prior_month_variance')
    op.drop_column('bugmonths', 'bugs_debuggers_n_irc_messages_undirected_prior_month_variance')
    op.drop_column('bugmonths', 'bugs_debuggers_n_bugs_contributed_to_prior_month_avg')
    op.drop_column('bugmonths', 'bugs_debuggers_n_history_events_focal_prior_month_variance')
    op.drop_column('bugmonths', 'bugs_debuggers_n_history_events_other_prior_month_avg')
    op.drop_column('bugmonths', 'bugs_debuggers_n_irc_messages_undirected_cumulative')
    op.drop_column('bugmonths', 'bugs_debuggers_n_history_events_other_past_monthly_avg')
    op.drop_column('bugmonths', 'bugs_debuggers_n_history_events_focal_cumulative')
    op.drop_column('bugmonths', 'bugs_debuggers_n_irc_messages_directed_cumulative')
    op.drop_column('bugmonths', 'bugs_debuggers_n_history_events_other_prior_month_variance')
    op.drop_column('bugmonths', 'bugs_debuggers_debugger_churn_past_monthly_avg')
    op.drop_column('bugmonths', 'bugs_debuggers_n_irc_messages_directed_prior_month_variance')
    op.drop_column('bugmonths', 'bugs_debuggers_n_irc_messages_undirected_prior_month_avg')
    op.drop_column('bugmonths', 'bugs_debuggers_n_history_events_focal_past_monthly_avg')
    op.drop_column('bugmonths', 'bugs_debuggers_n_reported_bugs_cumulative')
    op.drop_column('bugmonths', 'bugs_debuggers_n_history_events_other_cumulative')
    op.drop_column('bugmonths', 'bugs_debuggers_n_irc_links_prior_month_avg')
    op.drop_column('bugmonths', 'bugs_debuggers_n_irc_links_past_monthly_avg')
    op.drop_column('bugmonths', 'bugs_debuggers_n_bugs_contributed_to_past_monthly_avg')
    ### end Alembic commands ###
