"""new assignee graph vars

Revision ID: 4f1a9eeed5c3
Revises: 14c49ab07397
Create Date: 2013-04-18 13:36:21.208054

"""

# revision identifiers, used by Alembic.
revision = '4f1a9eeed5c3'
down_revision = '14c49ab07397'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bugmonths', sa.Column('assignee_effective_size_churn_cumulative', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('assignee_effective_size_churn_past_monthly_avg', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('assignee_effective_size_churn_prior_month', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('assignee_alter_churn_past_monthly_avg', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('assignee_efficiency_past_monthly_avg', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('assignee_alter_churn_cumulative', sa.Integer(), nullable=True))
    op.add_column('bugmonths', sa.Column('assignee_efficiency_prior_month', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('assignee_alter_churn_prior_month', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bugmonths', 'assignee_alter_churn_prior_month')
    op.drop_column('bugmonths', 'assignee_efficiency_prior_month')
    op.drop_column('bugmonths', 'assignee_alter_churn_cumulative')
    op.drop_column('bugmonths', 'assignee_efficiency_past_monthly_avg')
    op.drop_column('bugmonths', 'assignee_alter_churn_past_monthly_avg')
    op.drop_column('bugmonths', 'assignee_effective_size_churn_prior_month')
    op.drop_column('bugmonths', 'assignee_effective_size_churn_past_monthly_avg')
    op.drop_column('bugmonths', 'assignee_effective_size_churn_cumulative')
    ### end Alembic commands ###
