"""undirected chats

Revision ID: 51a6d95c0ef
Revises: bba674a18ba
Create Date: 2013-04-24 11:33:29.261142

"""

# revision identifiers, used by Alembic.
revision = '51a6d95c0ef'
down_revision = 'bba674a18ba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('undirectedchats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dbid', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dbid'], ['debuggers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('undirectedchats')
    ### end Alembic commands ###
