"""colcols

Revision ID: 52d489d2daa9
Revises: 2f7044d499c3
Create Date: 2013-04-25 15:16:30.653935

"""

# revision identifiers, used by Alembic.
revision = '52d489d2daa9'
down_revision = '2f7044d499c3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_reported_bugs_prior_month_variance', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_reported_bugs_prior_month_avg', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bugmonths', 'bugs_debuggers_n_reported_bugs_prior_month_avg')
    op.drop_column('bugmonths', 'bugs_debuggers_n_reported_bugs_prior_month_variance')
    ### end Alembic commands ###
