"""changed debuggermonths columns

Revision ID: 572da8d82c38
Revises: 21ca52dc7a
Create Date: 2013-04-20 16:41:29.146616

"""

# revision identifiers, used by Alembic.
revision = '572da8d82c38'
down_revision = '21ca52dc7a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
