"""added reporter id to bugs

Revision ID: bba674a18ba
Revises: 468781521a70
Create Date: 2013-04-24 10:34:58.904642

"""

# revision identifiers, used by Alembic.
revision = 'bba674a18ba'
down_revision = '468781521a70'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bugs', sa.Column('reporter_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bugs', 'reporter_id')
    ### end Alembic commands ###
