"""last of quarterly variables

Revision ID: c1966d114c4
Revises: 43704ef419c6
Create Date: 2013-06-30 16:53:36.659477

"""

# revision identifiers, used by Alembic.
revision = 'c1966d114c4'
down_revision = '43704ef419c6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_irc_links_prior_quarter_avg', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_irc_messages_undirected_quarterly_cumulative', sa.Integer(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_debugger_churn_prior_quarter', sa.Integer(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_irc_links_past_quarterly_avg', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_history_events_focal_quarterly_cumulative', sa.Integer(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_history_events_other_prior_quarter_variance', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_irc_messages_directed_prior_quarter_variance', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_irc_messages_directed_quarterly_cumulative', sa.Integer(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_bugs_contributed_to_quarterly_cumulative', sa.Integer(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_debugger_churn_past_quarterly_avg', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_debuggers_quarterly_cumulative', sa.Integer(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_debuggers_past_quarterly_avg', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_debuggers_prior_quarter', sa.Integer(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_debugger_churn_quarterly_cumulative', sa.Integer(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_bugs_contributed_to_prior_quarter_avg', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_irc_messages_directed_past_quarterly_avg', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_irc_messages_undirected_prior_quarter_avg', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_bugs_contributed_to_past_quarterly_avg', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_history_events_other_quarterly_cumulative', sa.Integer(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_history_events_focal_prior_quarter_avg', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_irc_links_prior_quarter_variance', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_irc_messages_directed_prior_quarter_avg', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_bugs_contributed_to_prior_quarter_variance', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_irc_messages_undirected_past_quarterly_avg', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_history_events_focal_prior_quarter_variance', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_history_events_other_past_quarterly_avg', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_irc_links_quarterly_cumulative', sa.Integer(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_history_events_focal_past_quarterly_avg', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_irc_messages_undirected_prior_quarter_variance', sa.Float(), nullable=True))
    op.add_column('bugmonths', sa.Column('bugs_debuggers_n_history_events_other_prior_quarter_avg', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bugmonths', 'bugs_debuggers_n_history_events_other_prior_quarter_avg')
    op.drop_column('bugmonths', 'bugs_debuggers_n_irc_messages_undirected_prior_quarter_variance')
    op.drop_column('bugmonths', 'bugs_debuggers_n_history_events_focal_past_quarterly_avg')
    op.drop_column('bugmonths', 'bugs_debuggers_n_irc_links_quarterly_cumulative')
    op.drop_column('bugmonths', 'bugs_debuggers_n_history_events_other_past_quarterly_avg')
    op.drop_column('bugmonths', 'bugs_debuggers_n_history_events_focal_prior_quarter_variance')
    op.drop_column('bugmonths', 'bugs_debuggers_n_irc_messages_undirected_past_quarterly_avg')
    op.drop_column('bugmonths', 'bugs_debuggers_n_bugs_contributed_to_prior_quarter_variance')
    op.drop_column('bugmonths', 'bugs_debuggers_n_irc_messages_directed_prior_quarter_avg')
    op.drop_column('bugmonths', 'bugs_debuggers_n_irc_links_prior_quarter_variance')
    op.drop_column('bugmonths', 'bugs_debuggers_n_history_events_focal_prior_quarter_avg')
    op.drop_column('bugmonths', 'bugs_debuggers_n_history_events_other_quarterly_cumulative')
    op.drop_column('bugmonths', 'bugs_debuggers_n_bugs_contributed_to_past_quarterly_avg')
    op.drop_column('bugmonths', 'bugs_debuggers_n_irc_messages_undirected_prior_quarter_avg')
    op.drop_column('bugmonths', 'bugs_debuggers_n_irc_messages_directed_past_quarterly_avg')
    op.drop_column('bugmonths', 'bugs_debuggers_n_bugs_contributed_to_prior_quarter_avg')
    op.drop_column('bugmonths', 'bugs_debuggers_debugger_churn_quarterly_cumulative')
    op.drop_column('bugmonths', 'bugs_debuggers_n_debuggers_prior_quarter')
    op.drop_column('bugmonths', 'bugs_debuggers_n_debuggers_past_quarterly_avg')
    op.drop_column('bugmonths', 'bugs_debuggers_n_debuggers_quarterly_cumulative')
    op.drop_column('bugmonths', 'bugs_debuggers_debugger_churn_past_quarterly_avg')
    op.drop_column('bugmonths', 'bugs_debuggers_n_bugs_contributed_to_quarterly_cumulative')
    op.drop_column('bugmonths', 'bugs_debuggers_n_irc_messages_directed_quarterly_cumulative')
    op.drop_column('bugmonths', 'bugs_debuggers_n_irc_messages_directed_prior_quarter_variance')
    op.drop_column('bugmonths', 'bugs_debuggers_n_history_events_other_prior_quarter_variance')
    op.drop_column('bugmonths', 'bugs_debuggers_n_history_events_focal_quarterly_cumulative')
    op.drop_column('bugmonths', 'bugs_debuggers_n_irc_links_past_quarterly_avg')
    op.drop_column('bugmonths', 'bugs_debuggers_debugger_churn_prior_quarter')
    op.drop_column('bugmonths', 'bugs_debuggers_n_irc_messages_undirected_quarterly_cumulative')
    op.drop_column('bugmonths', 'bugs_debuggers_n_irc_links_prior_quarter_avg')
    ### end Alembic commands ###
